RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Controllers/CheckListController.cs
using AppBradyReq.Models;
using AppBradyReq.Services.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppBradyReq.Controllers
{
    public class CheckListController : Controller
    {
        // GET: CheckList

        public ActionResult Cliente()
        {
            List<ClienteModel> cliente = new List<ClienteModel>();

            CadastroDAO cadastroDAO = new CadastroDAO();

            cliente = cadastroDAO.GetCliente_All();

            return View("Cliente", cliente);
        }

        public ActionResult SearchClienteReq()
        {
            return View("SearchClienteReq");
        }

        public ActionResult PesquisaPeloCNPJ(string searchCNPJ)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            List<RequisitoModel> searchResults = cadastroDAO.PesquisaPeloCNPJ(searchCNPJ);

            if (searchResults.ToList().Count() > 0)
            {
                Session["CNPJ"] = searchCNPJ;
            }

            return View("ClienteRequisito", searchResults);
        }

        public ActionResult ListaItem( int cliente,  int id)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            List<RequisitoItemModel> listaItens = cadastroDAO.BuscaListaItens(cliente, id);

            return View("ListaItemdoRequisito", listaItens);
        }

        public ActionResult Create(int cliente, int id_requisito, int id_item)
        {

            CadastroDAO cadastroDAO = new CadastroDAO();

            cadastroDAO.CreateRequisitoCliente(cliente, id_requisito, id_item);

            List<RequisitoModel> searchResults = cadastroDAO.PesquisaPeloCodigo(cliente);

            return View("ClienteRequisito", searchResults);
        }

        public ActionResult ExcluirItem(int cliente, int id)
        {

            CadastroDAO cadastroDAO = new CadastroDAO();

            cadastroDAO.ExcluirRequisitoCliente(cliente, id);

            List<RequisitoModel> searchResults = cadastroDAO.PesquisaPeloCodigo(cliente);

            return View("ClienteRequisito", searchResults);

        }


        public ActionResult EnviaEmail()
        {

            return View("EnviaEmail");
        }


    }
}

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppBradyReq.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Menu()
        {
            ViewBag.Message = "Escolha uma opção";
          
            if (Session["Usuario"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                return View("MenuForm");
            }
        }

    }
}

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Controllers/MapeadoController.cs
using AppBradyReq.Models;
using AppBradyReq.Services.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppBradyReq.Controllers
{
    public class MapeadoController : Controller
    {
        // GET: Mapeado
        public ActionResult Mercado()
        {
            List<MercadoModel> mercado = new List<MercadoModel>();

            CadastroDAO cadastroDAO = new CadastroDAO();

            mercado = cadastroDAO.GetMercado_All();

            return View("Mercado", mercado);
        }


        public ActionResult Clientes(int id)
        {
            List<ClienteModel> clientes = new List<ClienteModel>();

            CadastroDAO cadastroDAO = new CadastroDAO();

            clientes = cadastroDAO.GetLista_Clientes(id)
;
            return View("Clientes", clientes);
        }
    }
}

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<style>
    .img_home {
        display:block;
        margin:auto
    }
    .button_plus_area {
        display: block;
        width: 100px;
        float: right;
    }
    .button_plus {
        border-radius: 30px;
        font-size: 30px;
        width: 45%;
        background-color: limegreen;
        color: whitesmoke;
        border: none;
    }
</style>

<!--
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
-->
<h5>@Session["Usuario"]</h5>



<div >
    <div class="row"> 
     <div class="col-md-12">
        <img class="img_home" src="~/Content/Images/Farol.png" />
         </div>
    </div>
    
    <div class="row">
        <div class="button_plus_area">
        <input class="button_plus" type="button" value="+" onclick="location.href='@Url.Action("Menu", "Home")'" />
        </div>
    </div>

</div>



    <!--
    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>




        </div>
    </div>

        -->

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Views/Home/MenuForm.cshtml
@{
    ViewBag.Title = "MenuForm";

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .button_area {
        margin: auto;
        display: block;
        width: 200px;
        padding: 20px;
    }

    .btn {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 150px;
    }

</style>


<div class="container-fluid" style="margin-top: 20%;">

    <div class="row">
        <div class="button_area ">
            <input type="button" class="btn btn-success" value="Check List" onclick="location.href='@Url.Action("SearchClienteReq", "CheckList")'" />
        </div>
    </div>

    <div class="row">
        <div class="button_area ">
            <input type="button" class="btn btn-primary" value="Req. Mapeados" onclick="location.href='@Url.Action("Mercado", "Mapeado")'" />
        </div>
    </div>
</div>