RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Controllers/CadastroController.cs
using AppBradyReq.Models;
using AppBradyReq.Services.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppBradyReq.Controllers
{
    public class CadastroController : Controller
    {
        // Glossario
        public ActionResult Glossario()
        {
            List<GlossarioModel> glossario = new List<GlossarioModel>();

            CadastroDAO cadastroDAO = new CadastroDAO();

            glossario = cadastroDAO.GetGlossario_All();

            return View("Glossario", glossario);
        }

        public ActionResult Details(int id)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            GlossarioModel glossario = cadastroDAO.GetGlossario_One(id);


            return View("Details", glossario);
        }

        public ActionResult Create()
        {
            GlossarioModel glossario = new GlossarioModel();

            return View("GlossarioForm", glossario);
        }
  
        public ActionResult Edit( int id)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            GlossarioModel glossario = cadastroDAO.GetGlossario_One(id);

            return View("GlossarioForm", glossario);
        }

        public ActionResult Delete(int id)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            cadastroDAO.Delete(id);

            List<GlossarioModel> glossario = cadastroDAO.GetGlossario_All();


            return View("Glossario", glossario);
        }

        [HttpPost]
        public ActionResult ProcessCreate(GlossarioModel glossario)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();

            cadastroDAO.CreateOrUpdate(glossario);

            return View("Details", glossario);
        }

        public ActionResult SearchForm()
        {
            return View("SearchForm");
        }

        public ActionResult PesquisaPeloTitulo(string searchTitulo)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();
            List<GlossarioModel> searchResults = cadastroDAO.PesquisaPeloTitulo(searchTitulo);
            return View("Glossario", searchResults);
        }

        public ActionResult PesquisaPelaDescricao(string searchDescricao)
        {
            CadastroDAO cadastroDAO = new CadastroDAO();
            List<GlossarioModel> searchResults = cadastroDAO.PesquisaPelaDescricao(searchDescricao);
            return View("Glossario", searchResults);
        }

        // Item do Requisito
        public ActionResult Item()
        {
            List<ItemModel> item = new List<ItemModel>();

            CadastroDAO cadastroDAO = new CadastroDAO();

            item = cadastroDAO.GetItem_All();

            return View("Item", item);
        }






    }
}

RequisitosClientes/Projeto/AppBradyReq/AppBradyReq/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    .navMenu {
        background-color: #013775 !important;
    }

    li a {
        color: white !important;
        font-size: 18px;
    }

    li a:hover {
        color: gray !important;

    }

</style>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>



<body>
    <div class="navMenu navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>



                <a href='@Url.Action("Index", "Home")'>
                    <img src='@Url.Content("~/Content/Images/Brady.png")' />
                </a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
           
                    <li>
                        <a href='@Url.Action("SearchForm", "Cadastro")'>
                            <img src='@Url.Content("~/Content/Images/Lupa.png")' />
                        </a>   
                    </li>

                    <li>
                        @if (Session["Usuario"] == null)
                        {

                            @Html.ActionLink("Entrar", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
                        }
                        else
                        {
                            @Html.ActionLink("Sair", "Logout", "Login", new { area = "" }, new { @class = "navbar-brand" })

                        }
                    </li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BradyCorp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

</body>
</html>